namespace: logicmonitor
name: integration
version: 1.3.1
readme: README.md
authors:
  - Ansible (github.com/ansible)
description: Collection for LogicMonitor Ansible integration
license_file: LICENSE
tags:
  - logicmonitor
  - lm
  - monitoring
  - integration
repository: "https://github.com/ansible-collections/logicmonitor"
homepage: https://logicmonitor.com